### ISSUE TITLE
연결기업이 없는 회사의 경우 finstate_all 함수 응답 없음

### ISSUE THREAD

**Issue by Kisgnues** [FinanceData/OpenDartReader#11]
삼성바이오로직스와 같이 연결기업이 없는 회사는 finstate_all 함수가 응답하지 않습니다.

**Comment by FinanceData** [comment]
fs_div 에서 재무제표가 연결인지 별도인지를 지정합니다.
('CFS'=연결제무제표, 'OFS'=별도(개별)제무제표)

```python
dart.finstate_all(corp, bsns_year, reprt_code='11011', fs_div='CFS')
```

또한 0.0.8 에서 연결제무제표 데이터가 없는 경우(연결회사가 없는 경우) 자동으로 별도제무제표(fs_div='OFS') 데이터를 가져오도록 개선하였습니다.

See also https://github.com/FinanceData/OpenDartReader/wiki/Release-Note-0.0.8
