### ISSUE TITLE
공시검색 함수 list()의 final 변수 관련

### ISSUE THREAD

**Issue by tyolee** [FinanceData/OpenDartReader#17]
dart.py 의 list 함수의 시그니처에는 final=True로 되어 있습니다.

의미상 최종 보고서를 가져오는것이 기본값인 것으로 보입니다.

다만, 그 아래 주석에 다음과 같이 적혀 있습니다.

* final: 최종보고서 여부 (기본값: False)

또한 QuickStart에도 의미와 다르게 최종보고서 조회한다는 내용에 final=False로 들어가 있습니다.

# 삼성전자 1999년~2019년 모든 정기보고서(최종보고서) (82건)
dart.list('005930', start='1999-01-01', end='2019-12-31', kind='A', final=False) 

마지막으로 final변수에 대해 매뉴얼을 확인하고자 했는데 매뉴얼에는 final변수에 대한 설명이 빠져 있습니다.

동작에는 이상이 없는듯 하지만, 수정이 필요해 보입니다.

**Comment by FinanceData** [comment]
Release 0.2.0 에서 다소 많은 업데이트가 이루어졌고, 문서를 다시 정리하였습니다.
관심과 이슈 라이징 감사합니다.
