### ISSUE TITLE
finstate_all() 함수의 동작 문제

### ISSUE THREAD

**Issue by tyolee** [FinanceData/OpenDartReader#18]
dart.py 안에 있는 함수

    def finstate_all(self, corp, bsns_year, reprt_code='11011', fs_div='CFS'):
        corp_code = self.find_corp_code(corp)
        df = dart_finstate.finstate_all(self.api_key, corp_code, bsns_year, reprt_code=reprt_code, fs_div=fs_div)
        if len(df):
            return df
        return dart_finstate.finstate_all(self.api_key, corp_code, bsns_year, reprt_code=reprt_code, fs_div='OFS')

여기서  CFS없이 OFS만 있는 기업에 대해서 fs_div를 생략하고 호출하면

의도는 CFS로 api 호출하고 결과가 row가 0개인 dataframe이고, 그때 다시 OFS를 명시해서 호출하도록 되어 있지만

실제로는 NoneType이 리턴되어 다음과 같은 예외가 떨어집니다.

  File "/opt/anaconda3/lib/python3.7/site-packages/OpenDartReader/dart.py", line 95, in finstate_all
    if len(df):
TypeError: object of type 'NoneType' has no len()

그리고 CFS 결과가 없으면 없는대로 리턴해야지, 암묵적으로 OFS결과를 가져오는 것도 단순 기능의 원칙과 좀 다른 기능을 하는것 같습니다.

확인 부탁 드립니다.

**Comment by JeongWonLim** [comment]
어떤글을 보고 보내신거죠?

Windows 10용 메일에서 보냄

보낸 사람: tyolee
보낸 날짜: 2020년 9월 21일 월요일 오후 11:09
받는 사람: FinanceData/OpenDartReader
참조: Subscribed
제목: [FinanceData/OpenDartReader] finstate_all() 함수의 동작 문제 (#18)

dart.py 안에 있는 함수
def finstate_all(self, corp, bsns_year, reprt_code='11011', fs_div='CFS'):

    corp_code = self.find_corp_code(corp)

    df = dart_finstate.finstate_all(self.api_key, corp_code, bsns_year, reprt_code=reprt_code, fs_div=fs_div)

    if len(df):

        return df

    return dart_finstate.finstate_all(self.api_key, corp_code, bsns_year, reprt_code=reprt_code, fs_div='OFS')

여기서 CFS없이 OFS만 있는 기업에 대해서 fs_div를 생략하고 호출하면
의도는 CFS로 api 호출하고 결과가 row가 0개인 dataframe이고, 그때 다시 OFS를 명시해서 호출하도록 되어 있지만
실제로는 NoneType이 리턴되어 다음과 같은 예외가 떨어집니다.
File "/opt/anaconda3/lib/python3.7/site-packages/OpenDartReader/dart.py", line 95, in finstate_all
if len(df):
TypeError: object of type 'NoneType' has no len()
확인 부탁 드립니다.

**Comment by FinanceData** [comment]
기업별로 연결/별도를 따로 제공하는지 개별만 제공하는지 미리 확인하기는 어렵습니다.

말씀주신 내용대로 명확하게 전달하기 위해 현재 선택한 보고서의 종류(reprt_code)와 연결개별구분(fs_div)을 출력하도록하여 도움이 되도록 하였습니다.

```python
reprt_code='11011', fs_div='CFS' (사업보고서, 연결제무제표)'
```

추가로, reprt_code 혹은 fs_div를 잘못 지정한 경우 지정 가능한 항목을 에러 메시지에 보여주도록 했습니다.

```python
ValueError: invalid reprt_code (use one of {'11013': '1분기보고서', '11012': '반기보고서', '11014': '3분기보고서', '11011': '사업보고서'}

ValueError: invalid fs_div (use one of {'CFS': '연결제무제표', 'OFS': '별도(개별)제무제표'}
```
