### ISSUE TITLE
사업보고서, 재무제표주석에서 특정 키워드 검색

### ISSUE THREAD

**Issue by SNU078991** [FinanceData/OpenDartReader#19]
예를 들어 사업보고서에서 '주요 제품 목록', '사업분야', '시장전망' 등의 키워드가 들어간 문단 또는 수치를 검색하고 싶은데 가능할까요? 재무제표 주석에서도 같은 작업이 가능한지 알고 싶습니다.

**Comment by FinanceData** [comment]
가능합니다. 다만, OpenDartReader 에 기능으로 추가하는 것은 검토하고 있지 않습니다.

sub_docs() 함수는 보고서 HTML 문서의 URL들을 반환하고,  
document()함수는 지정한 보고서의 HTML 문서 자체를 반환합니다.
여기까지는 OpenDartReader의 기능이구요.

이렇게 HTML문서를 가져오면,
1) BeautifulSoup 같은 파서로 내용을 분석하거나
2) tag를 제외한 텍스트만 추출하여 이 텍스트에 대해 정규식(re)을 사용해서 텍스트를 추출할 수 도 있습니다.
3) HTML 문서의 table을 분석하는 것도 좋은 방법 중의 하나 입니다.
