### ISSUE TITLE
개선: 단일회사 전체 재무제표 API

### ISSUE THREAD

**Issue by FinanceData** [FinanceData/OpenDartReader#2]
2020년 2월 OpenDART에 추가된 "단일회사 전체 재무제표정보" 조회 반영

https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS003&apiId=2019020

**Comment by icesw21** [comment]
안녕하세요, 우선 좋은 라이브러리를 만들어주셔서 감사합니다. 현재 전체 재무제표를 불러오는 함수는 업데이트 중이실까요? 염치불구 문의드려 봅니다. 감사합니다.

**Comment by FinanceData** [comment]
Release 0.0.6 에 추가되었습니다.

더 상세한 내용은 아래 문서를 참고하세요.
https://github.com/FinanceData/OpenDartReader/wiki/Release-Note-0.0.6
