### ISSUE TITLE
재무제표의 경우 2015년 데이터 부터 가져올수 있는걸까요?

### ISSUE THREAD

**Issue by pj9039** [FinanceData/OpenDartReader#21]
안녕하세요.

아래 코드와 같이 2012년 삼성전자의 재무제표를 가져오려고 시도하였지만 None값이 반환되네요.
혹시 다른 방법이 있을까요?
```python
import OpenDartReader

api_key = ''

dart = OpenDartReader(api_key) 

df = dart.finstate("005930", 2012)
print(df)
```
2015년 이후 데이터는 잘 받아오는것 같습니다.

**Comment by Garden-L** [comment]
다트 오픈 api는 2015년 이후만 조회가능 하도록 지원하고 있습니다

**Comment by FinanceData** [comment]
> 다트 오픈 api는 2015년 이후만 조회가능 하도록 지원하고 있습니다

답변 감사합니다. 

앞서 말씀 주신 바와 같이, OpenDART API는 2015년 이후 부터 데이터를 제공하고 있습니다.
예외 메시지(안내 메시지)를 보강하도록 하겠습니다.
