### ISSUE TITLE
개선 - 데이터 제공 범위에 대한 안내 메시지  

### ISSUE THREAD

**Issue by FinanceData** [FinanceData/OpenDartReader#22]
OpenDART API는 2015년 이후 부터 데이터를 제공하고 있음. 제공되지 않는 범위의 데이터를 요청하는 경우
예외 메시지(안내 메시지)를 보강

**Comment by skindryang** [comment]
> OpenDART API는 2015년 이후 부터 데이터를 제공하고 있음. 제공되지 않는 범위의 데이터를 요청하는 경우
> 예외 메시지(안내 메시지)를 보강

2010년이나 2011년부터 2014년 까지의 자료를 볼려면 어떻게 해야하나요? (15년자료에 14년 13년 자료가 나오긴 하지만...)

**Comment by FinanceData** [comment]
재무데이터에서 사업년도를 지정하는 함수의 경우 2015년 이전인지 구분하여 에러메시지에 다음과 같이 출력하도록 수정하였습니다.

```python
dart.finstate('삼성전자', 2014) 

{'status': '013', 'message': '조회된 데이타가 없습니다.'}
전자공시의 재무데이터는 2015년 이후 데이터를 제공합니다
```

의견 감사합니다.
