### ISSUE TITLE
재무정보의 일관성, 누락 문제

### ISSUE THREAD

**Issue by stat17-hb** [FinanceData/OpenDartReader#23]
finstate()와 finstate_all() 함수를 이용하다 발견한 문제점을 공유드립니다.

+ 카카오(035720)는 매출액이 항목에 없음
+ 네이버(035420)는 판관비가 항목에 없음
+ KB금융(105560), 신한지주(055550), SK바이오팜(326030), 맥쿼리인프라(088980) 등은 finstate_all, finstate 모두 조회 안됨
+ 삼성전기(009150) 등은 현금흐름 관련 항목 account_id가 부여 안됨

이런 문제들은 dart 쪽 API 문제라고 봐야 할까요?

**Comment by limsh87** [comment]
dart.document...(공시원문 조회) 관련 질문드립니다.
아시아퍼시픽11호(stock_code:083580/corp_code:00533793)의 2017.03 분기보고서(rcept_no:20170515003410), 2016.12 반기보고서(rcept_no:20170214000468) 가 조회되지 않습니다. 상장폐지이후라 그런가 했는데 그것도 아니네요.

**Comment by FinanceData** [comment]
관심과 코멘트 감사합니다.

몇 가지로 구분하여 검토하고 정리해 보았습니다.

## 데이터 항목 자체가 없는 경우
OpenDartReader는 제공되는 API 데이터를 그대로 가져옵니다. 아예 데이터가 없거나 에러가 발생하는 경우가 아니라면 API 에서 제공되는 데이터 그대로 라고 보시면 되겠습니다.

카카오(035720)는 매출액이 항목은 최근 년도에는 없으나 과거 년도에는 데이터가 있습니다.
네이버(035420) 판관비, 삼성전기(009150) account_id 항목도 마찬가지라고 보시면 되겠습니다.

## 금융업 재무데이터 제외
KB금융(105560), 신한지주(055550) 등 금융업종 데이터는 제공되지 않습니다. 

아래 URL 설명을 참고하시기 바랍니다.

https://opendart.fss.or.kr/guide/main.do?apiGrpCd=DS003

## 지정하는 범위
SK바이오팜(326030)의 경우 2020. 7 상장하였으므로 사업보고서는 없습니다.
다만 2020년 3분기 보고서는 아래와 같이 조회가 가능합니다.

```python
finstate(326030, 2020, reprt_code='11014') # 3분기 보고서
```

도움이 되셨길 바랍니다.
