### ISSUE TITLE
dart.document...공시원문 조회 문의드립니다.

### ISSUE THREAD

**Issue by limsh87** [FinanceData/OpenDartReader#24]
dart.document...(공시원문 조회) 관련 질문드립니다.
아시아퍼시픽11호(stock_code:083580/corp_code:00533793)의 2017.03 분기보고서(rcept_no:20170515003410), 2016.12 반기보고서(rcept_no:20170214000468) 가 조회되지 않습니다. 상장폐지이후라 그런가 했는데 그것도 아니네요.

**Comment by FinanceData** [comment]
다음 두 가지 모두 보완하고 수행확인하였습니다.
상폐와는 상관없이 접수번호(rcp_no)로 가능합니다.

```python
xml_text = dart.document('20170515003410')
xml_text 
```

```python
xml_text = dart.document('20170214000468')
xml_text 
```

이슈 라이징 감사합니다.
