### ISSUE TITLE
지분공시 rcept_no 관련 질문

### ISSUE THREAD

**Issue by limsh87** [FinanceData/OpenDartReader#25]
LS, 알파홀딩스 등 다수 기업의 지분공시 접수번호 series 조회시 한개의 접수번호가 아닌 두개의 접수번호가 조회됩니다.
아래와 같은 식으로요(아래는 LS의 경우입니다). 이때문에 접수번호로 조회하는 공시원문 등의 조회에서 오류가 납니다.

list = dart.list('LS', start='2015-01-01', kind = 'D', final=True)
rcp = list.rcept_no
print(rcp)
print(type(rcp))
print(type(rcp[0]))
rcp[0]
........................................................
0   20210108000843
1   20210107000209
3   20201218000626
..
...
97  2012103000073

Name : rcept_no, Length: 198, dtype: object
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
0   20210108000843
0   20191025000489
Name: rcept_no, dtype: object

**Comment by FinanceData** [comment]
FIX 하였습니다. 

```python
ls = dart.list('LS', start='2015-01-01', kind = 'D', final=True)
rcp = ls.rcept_no
print(rcp)
print(type(rcp))
print(type(rcp[0]))
rcp[0]
```

```
0      20221006000287
1      20221005000230
2      20220906000041
3      20220818000409
4      20220803000037
            ...      
246    20150303000237
247    20150217000387
248    20150217000384
249    20150108000222
250    20150106000073
Name: rcept_no, Length: 251, dtype: object
<class 'pandas.core.series.Series'>
<class 'str'>
```

concat한 결과에 index가 중복되어 생긴 현상이 었습니다.
이슈 라이징 감사합니다.
