### ISSUE TITLE
지배기업의 소유주에게 귀속되는 당기순이익(손실)의 account_id 또는 account_nm이 식별이 어려운 경우가 발생합니다.

### ISSUE THREAD

**Issue by stat17-hb** [FinanceData/OpenDartReader#31]
네이버(035420)의 2019년, 2020년 사업보고서(11011)를 조회해보면 지배기업의 소유주에게 귀속되는 당기순이익(손실) 계정이 정확하게 식별되지 않습니다.

<html>
<body>

account_id | account_nm | thstrm_nm | thstrm_amount
-- | -- | -- | --
 ifrs-full_ProfitLoss | 당기순이익(손실) | 제 21 기 | 396821062465
-표준계정코드 미사용- | 계속영업이익 | 제 21 기 | 586641122833
-표준계정코드 미사용- | 중단영업이익(손실) | 제 21 기 | -3589218184

</body>
</html>

<html>
<body>

account_id | account_nm | thstrm_nm | thstrm_amount
-- | -- | -- | --
 ifrs-full_ProfitLoss | 당기순이익(손실) | 제 22 기 | 844996977149
-표준계정코드 미사용- | 계속영업이익 | 제 22 기 | 1144888651236
-표준계정코드 미사용- | 중단영업손실 | 제 22 기 | -142801884857

</body>
</html>

당기순이익(손실) 다음에 조회되는 계속영업이익, 중단영업이익(손실) or 중단영업손실 이 부분이 지배기업의 소유주에게 귀속되는 당기순이익(손실) 부분인 것 같은데 이 부분에 대한 account_id, account_nm의 처리가 필요해 보입니다.

**Comment by FinanceData** [comment]
공시된 데이터를 그대로 가져오는 것 뿐이어서 임의로 변경하거나 가공하기 어렵습니다.
(공시 데이터 자체가 개별회사에서 작성하여 보고하는 것이고, 또한 회사마다 다소 차이가 있습니다)

다만, 항목들 중에 ' 지배기업의 소유주에게 귀속되는'으로 언급되는 내용이 있으므로 함께 참조할 수 있을 듯 합니다.

![image](https://user-images.githubusercontent.com/806717/195097494-c42fa44b-6b38-4e40-877c-7d86cdf2ad3c.png)
