### ISSUE TITLE
dart.document 의 에러

### ISSUE THREAD

**Issue by sangkim22** [FinanceData/OpenDartReader#33]
예시문 적용하여 
xml_text = dart.document("20190401004781") 해도 

UnicodeEncodeError: 'charmap' codec can't encode characters in position 220-224: character maps to <undefined>

에러 메세지를 받습니다

**Comment by FinanceData** [comment]
최근 업데이트에서 FIX 하였습니다.

![image](https://user-images.githubusercontent.com/806717/195018365-08c2d8f3-fadf-4f4f-b541-f9d3f625ccd0.png){: width="60%"}
