### ISSUE TITLE
opendart설치 및 사용 관련 질문드립니다.

### ISSUE THREAD

**Issue by cjsaudcjswo** [FinanceData/OpenDartReader#34]
안녕하세요.
opendart를 사용하고자 하는 파이썬 초보입니다.

 opendart라는 프로그래밍 코드를 통해,
기업 재무제표 분석에 활용하고자 합니다.

관련 링크 첨부드립니다.

 https://github.com/FinanceData/OpenDartReader

(질문)
여기서, opendart 설명부분을 보시면,
이렇게 나와있습니다. 

-------------------------------------------
다음과 같이 설치 합니다.

pip install opendartreader
이미 설치되어 있고 업그레이드가 필요하다면 다음과 같이 설치합니다.

pip install --upgrade opendartreader 
-------------------------------------------

* 여기서,

pip install opendartreader
pip install --upgrade opendartreader 이런 것들을

cmd에 치면 자동으로 opendartreader가 설치되는 것인지요?

즉, opendartreader를 설치하고 업그레이드를 하기 위해

pip install opendartreader
pip install --upgrade opendartreader

이 문구들을
파이썬이나 아나콘다에 치는 것인지
아니면
cmd에 치는 것인지

만약 cmd에 치는 것이라면
반드시 cmd를 관리자 권한으로 실행해야 하는 것인지 질문드립니다.

(질문)
 https://github.com/FinanceData/OpenDartReader  이 링크에 들어가보시면,

opendartreader의 폴더 라이브러리와 해당 모듈들이 있습니다.
이것들을 제 컴퓨터에 다운로드 받아야겠죠.

그런데, 이것들을
제 컴퓨터상 아무 공간에나 다운로드 받아도 상관이 없는 것인지
아니면
반드시 어떤 지정된 경로에 다운로드 받아야만

opendartreader를 사용할 수 있는 것인지
여쭙니다.

(질문)
만약, opendartreader를 설치까지 모두 완료하였고,
사용을 위한 모든 세팅이 완성되었다고 가정하겠습니다.

그러면,
본격적으로 코드들을 활용해야 할 텐데,

예컨대 이런 코드가 있습니다.

----------------------------------------------------------------
import OpenDartReader

# ==== 0. 객체 생성 ====
# 객체 생성 (API KEY 지정) 
api_key = 'a81e18ac719d1e1e4ec2899ef25a737ab6cbb4c7'

dart = OpenDartReader(api_key) 

# == 1. 공시정보 검색 ==
# 삼성전자 2019-07-01 하루 동안 공시 목록 (날짜에 다양한 포맷이 가능합니다)
dart.list('005930', end='2019-7-1')
----------------------------------------------------------------

그러면, 파이썬이나 아나콘다에
저 코드를 입력한 다음,

ctrl + shift + B 를 누르면 되는지요?

print문이 없는데도

import OpenDartReader
api_key = 'a81e18ac719d1e1e4ec2899ef25a737ab6cbb4c7'
dart = OpenDartReader(api_key) 
dart.list('005930', end='2019-7-1')

이 코드만으로도
삼성전자 2019-07-01 하루 동안 공시 목록이 출력 가능한지요?

(추가질문)
만약 가능하다면,
파이썬 창에서 뿐만 아니라

메모장이나 엑셀 파일로 이 출력 내용을 저장하려면
어떻게 해야 하는지도 여쭙니다.

초보적인 질문 죄송합니다 ㅠㅠ

귀중한 가르침 정말 감사드립니다.

항상 감사드리며,
오늘도 좋은 하루 되세요 ^^

너무 초보적인 질문이라 죄송합니다 ㅠㅠ

**Comment by jtrimind** [comment]
1. python을 설치하셨으면 pip도 설치가 되셨을 겁니다. cmd에서 `pip install opendartreader`를 치면 설치가 됩니다.
2. pip로 opendartreader를 설치하셨기 때문에 소스코드를 다운받을 필요는 없습니다.
3. `dart.list('005930', end='2019-7-1')`을 실행하면 공시 목록이 리턴됩니다. 출력을 하려면 print를 해야하는데 만약 쥬피터 노트북을 사용하신다면 마지막 실행 결과가 예쁘게 출력이 될 겁니다.
4. 메모장으로 출력하시려면 파이썬 파일 읽고 쓰는 방법을 찾아보세요. 액셀로 저장하려면 파이썬 csv 모듈을 찾아보세요.

**Comment by cjsaudcjswo** [comment]
> 1. python을 설치하셨으면 pip도 설치가 되셨을 겁니다. cmd에서 `pip install opendartreader`를 치면 설치가 됩니다.
> 2. pip로 opendartreader를 설치하셨기 때문에 소스코드를 다운받을 필요는 없습니다.
> 3. `dart.list('005930', end='2019-7-1')`을 실행하면 공시 목록이 리턴됩니다. 출력을 하려면 print를 해야하는데 만약 쥬피터 노트북을 사용하신다면 마지막 실행 결과가 예쁘게 출력이 될 겁니다.
> 4. 메모장으로 출력하시려면 파이썬 파일 읽고 쓰는 방법을 찾아보세요. 액셀로 저장하려면 파이썬 csv 모듈을 찾아보세요.


=============================================================================
네 귀중한 답변 
정말 감사드립니다.

몇 가지 궁금한 부분이 있는데
이 부분만 도와주신다면

정말 감사드리겠습니다.

**********
(질문)
cmd에서
pip install opendartreader를 입력하여 설치하는 방식은,

* 별도의 폴더나 경로 지정을
안 해줘도 괜찮은지요?

제가 알기로는,
제 컴퓨터상의 여러 폴더들 중,

pip파일이 있는 폴더에다가
경로지정을 해야만한다고 들어서
여쭙니다.


*만약 이게 맞다면 
(반드시, pip파일이 있는 폴더에다가만
설치해야 한다면)

opendartreader를 설치하여 사용 후,
시간이 흘러,

pip파일을 다른 폴더에다가로 이동했을 경우
opendartreader역시 다시 설치해야 하는지요?

**********
(질문)
저는 파이썬 3.10버젼을 사용 중입니다.

제가 알기로는
3.4버젼 이상부터는

파이썬 설치시
pip역시 자동으로 설치되는 것으로 알고 있는데,

제가 사용하는 3.10버젼은
3.4버젼보다 높은 버젼인지 낮은 버젼인지 여쭙니다.

**********
(질문)
제 컴퓨터에서 cmd를 실행시킨 후,

opendartreader를 설치하기 위한 부분입니다.

● 제 컴퓨터의 cmd에
get-pip.py라고 입력하면

python이라고 뜹니다.

이 말은,
제 컴퓨터에 pip가 정상적으로 설치되어있다는 뜻인지요?


● 그래서,
pip install opendartreader를 입력하니,

"'pip'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다."라고 뜹니다.

이 오류의 원인과 해결방법을 여쭙니다.

**********
(질문)
opendartreader 업그레이드 관련하여 여쭙니다.

pip install --upgrade opendartreader를 cmd에 입력하면
업그레이드가 가능하다고 합니다.

이 업그레이드는
한 달에 한 번, 혹은 두 달에 한 번 정도

주기적으로 제가 그냥,

그냥 cmd에
pip install --upgrade opendartreader을 입력해주는 식으로
업데이트를 해 나가면 되는지요? 

**********
귀중한 답변 감사드립니다.
오늘도 좋은 하루 되세요 ^^

너무 초보적인 질문이라 죄송합니다.

**Comment by jtrimind** [comment]
1. pip를 옮겨보는 등의 행위를 안해봐서 모르겠습니다.
2. `3.10`은 `3.4`보다 높은 버전입니다.
3. `get-pip.py`라는 파일이 무엇인지 모르겠습니다. `pip`를 쳤을 때 저런 로그가 뜬다면 아마 python 설치했을 때 `"Add Python 3.10 to Path"`를 체크하지 않았을 가능성이 큽니다. 삭제후 재설치를 권합니다.
4. 네. 근데 동작에 문제가 없는 이상 업데이트를 할 이유도 없겠죠.
