### ISSUE TITLE
주피터노트북으로 OpendartReader를 사용하려는데, 결과값이 출력 안됩니다. (초보 질문)

### ISSUE THREAD

**Issue by cjsaudcjswo** [FinanceData/OpenDartReader#35]
안녕하세요.
좋은 프로그램 만들어주셔서 감사드립니다.

다름이 아니라,
주피터노트북으로 OpendartReader를 사용하려는데, 결과값이 출력 안됩니다.

예컨대,
cmd에서
pip opendartreader를 입력하여  opendartreader 설치한 다음,

삼성전자 2019-07-01 하루 동안 공시 목록을 불러오기 위하여

주피터노트북 상에

import OpenDartReader

api_key = 'aaaaaaaaaaaaaaaaaaaaaaaa' <<< 제 opendart api키라고 가정하겠습니다.

dart = OpenDartReader(api_key) 

a=dart.list('005930', end='2019-7-1')

print(a)

이런 식으로 코드를 입력한 후
Run버튼을 눌렀음에도 아무 반응이 일어나지 않습니다. 
(본 질문 관련하여, 제가 첨부드린 첨부 이미지 참조 부탁드리겠습니다.)

(참고로, 주피터노트북 상의 Run버튼 = 파이썬 상의 Start 디버깅 버튼이 맞는 것인지요? 만약 파이썬 상에서 코드 입력 후 결과값을 산출하려면 Start 디버깅을 클릭하는게 맞는지요?)

파이썬을 이제 막 처음 공부한 초보라 죄송합니다 ㅠㅠ

(질문)
결과값을 산출해내려면
어떻게 하여야 하는지 질문드립니다.
(물론, 그 결과값을 엑셀파일 등으로 저장하려면
pandas도 함께 사용하여야겠지만

단순히, 주피터노트북 상에서만
결과값을 보기를 원한다면 어떻게 하여야 하는지 여쭙니다.)

귀중한 답변
감사드립니다.

오늘도 좋은 하루 되세요 ^^

![Opendart Reader 질문](https://user-images.githubusercontent.com/52618715/147812442-6fe330d5-8cd9-4d27-afa7-948628388a99.PNG)

**Comment by kgcrom** [comment]
@cjsaudcjswo 안녕하세요.
얘기해주신 코드는 문제 없어 보이는데요, 첨부하신 주피터 노드북 파일에서 "Not Connected", "error" 가 보이는데
주피터 노트북 서버에 문제는 없는지 확인하면 좋을것 같습니다.

**Comment by FinanceData** [comment]
코드는 잘 작성하신 것 같습니다.
매번 import 하실 필요는 없습니다.

위 이미지 상태를 실행중에 멈춘것으로 보입니다.
Not connected 라고 표시 되네요.

우선은 도구 사용법등에 대해 조금만 더 연습해보시면 좋을 듯 합니다. 
다음과 같은 좋은 온라인 강좌들이 꽤 많이 있습니다.

https://www.inflearn.com/course/파이썬-주피터-노트북
