### ISSUE TITLE
dart.list() 출력 에러

### ISSUE THREAD

**Issue by iwstiger** [FinanceData/OpenDartReader#38]
dart.list() 를 활용하여 사업보고서를 출력했는데, 감사보고서 또는 연결감사보고서가 올라 옵니다. 어떻게 해야 할까요?
코드는 아래와 같습니다. k=0, 1, 6인 경우, 감사보고서가 올라 옵니다.

sec_ticker = '005930'
start_dt = '20140601'
end_dt='20220630'
rpt_list = dart.list(sec_ticker, start=start_dt, end=end_dt, kind='A', final='true')
result = rpt_list[rpt_list.rm=='연']
k = 0
input_text = dart.document(rct_no[rct_no.index[k]])
input_text

**Comment by FinanceData** [comment]
아래까지는 잘 수행 됩니다만 rct_no 가 무엇인지 위 내용만으로는 알 수 없네요. 

```python
sec_ticker = '005930'
start_dt = '20140601'
end_dt='20220630'
rpt_list = dart.list(sec_ticker, start=start_dt, end=end_dt, kind='A', final='true')
rpt_list
```

```python
sec_ticker = '005930'
start_dt = '20140601'
end_dt='20220630'
rpt_list = dart.list(sec_ticker, start=start_dt, end=end_dt, kind='A', final='true')
rpt_list
```

현재 issue 들을 정리중입니다.
혹시, 추가 질문이 있으시면 reopen 해주시면 되겠습니다.
