### ISSUE TITLE
dart.sub_docs(rcp_no)를 통해 연결재무제표 주석 하위 링크를 불러오지 못하는 오류(#초보)

### ISSUE THREAD

**Issue by monkey821** [FinanceData/OpenDartReader#39]
안녕하세요.
올려주신 패키지를 열심히 공부하고 있습니다.
Dart 홈페이지 리뉴얼 이후 
sub_report = dart.sub_docs(rcp_no)
print(sub_report)를 할 경우에,

로마숫자로 큰 카테코리 (1. 회사의 개요, 2. 사업의 내용, 3. 재무에 관한 사항)등만 불러오고,
연결재무제표 주석 등 하위 링크는 불러오지 못하고 있습니다.

업데이트가 되면 좋겠지만, 안된다면 제가 만들어 써봐야지 하고 공부를 시작했는데, 
뭐를 어디서부터 공부해야할지 막막하더라구요..
그래서 질문드리게 되었습니다.

1. 혹시 업데이트 계획 있으신가요??
2. 앞으로도 홈페이지가 업데이트 된다면, 패키지의 업데이트가 안될 경우 이용하지 못하게 되는데, 비전공자인 제가 직접 만들려면 어떤걸 공부해야 할까요??
3. 혹시 만들어두신 패키지 파일에 답이 담겨져 있지 않을까?? 하고 뜯어봤는데 제가 몰라서 안보이는 건지?? request를 활용하는건 알겠으나 .sub_docs가 어떻게 하위 링크를 불러오는지 작동기전??에 대한 부분은 찾지 못했는데 혹시 간략하게라도 어디를 찾아보면 나온다 라고 말씀해 주실 수 있으실까요??

**Comment by FinanceData** [comment]
수정반영하였습니다.

[Users Guide](https://nbviewer.org/github/FinanceData/OpenDartReader/blob/master/docs/OpenDartReader_users_guide.ipynb#7.-%ED%99%95%EC%9E%A5-%EA%B8%B0%EB%8A%A5) 에 조금 상세하게 정리하였습니다.

참고해보시고, 혹시 해결되지 않으면 현재 이슈를 다시 reopen 해주세요.

관심과 이슈라이징 감사합니다.

**Comment by monkey821** [comment]
안녕하세요 선생님.
답변 달아주셔서 정말 감사합니다.
업데이트 해주신 부분 참고하여 공부해보겠습니다.
User Guide에 상세히 정리해 주신점도 정말 감사합니다.
혹시 인터넷 강의 다시 진행하실 계획 있으신지 여쭤봐도 될까요??
이전에 우연히 인터넷 강의 여셨던 걸 구글링 하면서 발견했었습니다.
