### ISSUE TITLE
2023 2Q 문제

### ISSUE THREAD

**Issue by boulderphd** [FinanceData/OpenDartReader#48]
늘 감사하게 잘 쓰고 있습니다.

2023 2Q 재무정보 데이터는 언제쯤 upload가 되는지요?  

어떤 종목은 2Q 보고서가 나오는데, 어떤 종목들은 없다고 error가 발생합니다.

감사합니다.

**Comment by FinanceData** [comment]
재무데이터가 업데이트 되는 시점은 종목별(개별 회사별)로 다릅니다. 개별 회사별로 일정이 있습니다. "실적발표 일정"으로 검색해 보시면 관련 내용을 찾아 보실 수 있을 겁니다.

OpenDartReader 에서 제어하는 부분은 없구요. DART에 재무데이터가 게시되면 API를 통해 OpenDartReader에서 데이터를 보실 수 있을 것입니다.
