### ISSUE TITLE
정정공시 반영 기능

### ISSUE THREAD

**Issue by d1kjh** [FinanceData/OpenDartReader#7]
사업 보고서 정정공시가 발생하는 경우가 종종 있습니다. 대부분 경우 큰 차이는 아니지만 정확한 데이터를 위해 필요하다 생각합니다. 테스트케이스로 대한해운을 보시면 도움이 될 듯 합니다.

**Comment by FinanceData** [comment]
제안 의견 감사합니다.

말씀대로 정정공시가 꽤 발생합니다. 
이에 대응하기 위해 공시검색 API 의 list() 함수에 final 옵션이 있습니다. 정정공시가 발생한 경우 최종 보고서만 조회할지 모두를 조회할지에 대한 옵션입니다.

```python
dart.list(corp, start=None, end=None, kind='', kind_detail='', final=True)
```

https://bit.ly/2UqcOSJ

위 옵션이 생각하시는 이슈에 대한 해결책이 되지 않거나,
대한해운 케이스에 대해 조금 더 자세히 알려주시면 도움이 될 것 같습니다.

**Comment by d1kjh** [comment]
제 질문이 성급했습니다. 감사합니다-_-b
