### ISSUE TITLE
dart.finstate_all()에서 fs_div 선택 불가

### ISSUE THREAD

**Issue by JoohyunKang** [FinanceData/OpenDartReader#8]
현재 finstate_all에서 fs_div를 선택할 수 없게 되어있어서 (CFS로 되어있음),
종속기업이 없는 기업은 finstate_all을 할 시, 검색이 안되는 문제가 있습니다.

**Comment by FinanceData** [comment]
다음과 같이 FIX 합니다. 
알려주셔서 감사합니다.

```python
finstate_all(corp, bsns_year, reprt_code='11011', fs_div='CFS')
```

**Comment by FinanceData** [comment]
Release 0.0.8 추가 보강및 개선하였습니다.

https://github.com/FinanceData/OpenDartReader/wiki/Release-Note-0.0.8
